[build-system]
requires = ["setuptools>=62.0", "setuptools-git-versioning>=2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scikit-package"
dynamic=['version', 'dependencies']
authors = [
  { name="Simon J.L. Billinge", email="sb2896@columbia.edu" },
  { name="Sangjoon Lee", email="bobleesj@gmail.com" },
  { name="Andrew Yang", email="ay2546@columbia.edu" },
  { name="Caden Myers", email="cjm2304@columbia.edu" },
  { name="Tieqiong Zhang", email="tz2600@columbia.edu" },
]
maintainers = [
  { name="Simon J.L. Billinge", email="sb2896@columbia.edu" },
  { name="Sangjoon Lee", email="bobleesj@gmail.com" },
]
description = "A Python package standard and generator for scientific code. Use scikit-package to launch a new project or migrate existing ones to support the latest Python versions and streamline the process of distributing and maintaining your software package."
keywords = ['Package template', 'open-source software']
readme = "README.rst"
requires-python = ">=3.12, <3.15"
classifiers = [
        'Development Status :: 3 - Alpha',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',
        'Operating System :: MacOS :: MacOS X',
        'Operating System :: Microsoft :: Windows',
        'Operating System :: POSIX',
        'Operating System :: Unix',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.14',
        'Topic :: Scientific/Engineering :: Physics',
        'Topic :: Scientific/Engineering :: Chemistry',
]

[project.urls]
Homepage = "https://github.com/scikit-package/scikit-package/"
Issues = "https://github.com/scikit-package/scikit-package/issues/"

[tool.setuptools-git-versioning]
enabled = true
template = "{tag}"
dev_template = "{tag}"
dirty_template = "{tag}"

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)
include = ["*"]  # package names should match these glob patterns (["*"] by default)
exclude = []  # exclude packages matching these glob patterns (empty by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)

[tool.setuptools.dynamic]
dependencies = {file = ["requirements/pip.txt"]}

[project.scripts]
package = "scikit_package.scikit_package_app:main"
scikit-package = "scikit_package.scikit_package_app:main"

[tool.codespell]
exclude-file = ".codespell/ignore_lines.txt"
ignore-words = ".codespell/ignore_words.txt"
skip = "*.cif,*.dat"

[tool.docformatter]
recursive = true
wrap-summaries = 72
wrap-descriptions = 72

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.rst
  | \.txt
  | _build
  | buck-out
  | build
  | dist
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/
'''

[tool.pytest.ini_options]
addopts = [
    "--ignore={{ cookiecutter.github_repo_name }}",
]
